apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    tag: {{ .Values.image.tag }}
    revision: "{{ .Release.Revision }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - image: {{ .Values.image.org }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
        name: {{ .Chart.Name }}
        imagePullPolicy: Always
        env:
          - name: ORDERS_PROTO_PATH
            value: /home/node/app/proto/orders.proto
          - name: PRODUCTS_PROTO_PATH
            value: /home/node/app/proto/products.proto
          - name: ORDERS_SERVICE
            value: orders:50051
          - name: PRODUCTS_SERVICE
            value: products:50051
      restartPolicy: Always
